# classification_thresholds.yml
log10_beta_attenuation_thresholds:
  0:
    - -10
    - -6
  1:
    - -6
    - -5
  5:
    - -5
    - -4.3
  9:
    - -4.3
    - -3

linear_depolarization_thresholds:
  0:
    - 0
    - 0.2
  1:
    - 0.2
    - 0.35
  2:
    - 0.35
    - 0.5
  3:
    - 0.5
    - 1

class_combination_mapping:
  0: "clear & clear"
  1: "low density & liquid_droplets"
  2: "low density & snow"
  3: "low density & ice_crystals"
  4: "low density & graupel"
  5: "precipitation & liquid_droplets"
  6: "precipitation & snow"
  7: "precipitation & ice_crystals"
  8: "precipitation & graupel"
  9: "clouds & liquid_droplets"
  10: "clouds & snow"
  11: "clouds & ice_crystals"
  12: "clouds & graupel"
  1000: 'noisy'
  9999: 'Unclassified'

category_colors:
  # clear
  - 'xkcd:sky'
  # low density & liqui droplets
  - 'xkcd:light aqua'
  # low density & snow
  - 'xkcd:cream'
  # low density & ice_crystals
  - 'xkcd:pale lilac'
  # low density & graupel
  - 'xkcd:wheat'
  # precipitation & liquid_droplets 'xkcd:water blue'
  - '#619db0'
  # "precipitation & snow"
  - 'xkcd:light pink'
  # precipitation & ice crystals
  - 'xkcd:pastel red'
  # precipitation & graupel
  - 'xkcd:piss yellow'
  # clouds & liquid_droplets
  - 'xkcd:petrol'
  # clouds & snow
  - 'xkcd:grey purple'
  # clouds & ice_crystals
  - 'xkcd:red wine'
  # clouds & graupel
  - 'xkcd:browny orange'
  # Unclassified
  - 'black'
  # noisy 
  - 'grey'